[platformio]
; This file is used by the PlatformIO IntelliJ plugin to compile/upload the sketch.
; If you use a different board than Arduino Uno, change `board = ...` below.

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

; If upload fails, you can set the upload_port manually in the IDE UI.
; upload_port = /dev/tty.usbmodemXXXXXXX

